// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pomelo.DevOps.Triggers.Interval.Models;

#nullable disable

namespace Pomelo.DevOps.Triggers.Interval.Migrations
{
    [DbContext(typeof(TriggerContext))]
    [Migration("20221216143454_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pomelo.DevOps.Triggers.Interval.Models.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("JobDescriptionTemplate")
                        .HasColumnType("longtext");

                    b.Property<string>("JobNameTemplate")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PomeloDevOpsPipeline")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PomeloDevOpsProject")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Enabled", "IntervalMinutes", "LastTriggeredAt");

                    b.ToTable("Triggers");
                });
#pragma warning restore 612, 618
        }
    }
}
