// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pomelo.DevOps.Triggers.Scheduled.Models;

#nullable disable

namespace Pomelo.DevOps.Triggers.Scheduled.Migrations
{
    [DbContext(typeof(TriggerContext))]
    [Migration("20221215135304_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("Pomelo.DevOps.Triggers.Scheduled.Models.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobDescriptionTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobNameTemplate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PomeloDevOpsPipeline")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PomeloDevOpsProject")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.ToTable("Triggers");
                });
#pragma warning restore 612, 618
        }
    }
}
